name: Test

on: pull_request

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: yarn install
        run: |
          yarn install
          yarn build
          yarn test

# Failing beacuse virtual framebuffer not installed
#          yarn build-e2e
#          yarn test-e2e
